(function (global) {
  'use strict';

  // Extracted from app.js — per-Genki-chapter example sentences used by
  // both the Sentences flashcard mode (translate direction) and the
  // printable translation worksheets (scripts/render_sentence_html.py).
  global.TRANSLATE_SENTENCES = {
    3: [
      { ja: '私は毎日コーヒーを飲みます。', jaHtml: '<ruby>私<rp>(</rp><rt>わたし</rt><rp>)</rp></ruby>は<ruby>毎日<rp>(</rp><rt>まいにち</rt><rp>)</rp></ruby>コーヒーを<ruby>飲<rp>(</rp><rt>の</rt><rp>)</rp></ruby>みます。', en: 'I drink coffee every day.' },
      { ja: '山田さんは日本語を話します。', jaHtml: '<ruby>山田<rp>(</rp><rt>やまだ</rt><rp>)</rp></ruby>さんは<ruby>日本語<rp>(</rp><rt>にほんご</rt><rp>)</rp></ruby>を<ruby>話<rp>(</rp><rt>はな</rt><rp>)</rp></ruby>します。', en: 'Mr. Yamada speaks Japanese.' },
      { ja: '私は朝六時に起きます。', jaHtml: '<ruby>私<rp>(</rp><rt>わたし</rt><rp>)</rp></ruby>は<ruby>朝<rp>(</rp><rt>あさ</rt><rp>)</rp></ruby><ruby>六<rp>(</rp><rt>ろく</rt><rp>)</rp></ruby><ruby>時<rp>(</rp><rt>じ</rt><rp>)</rp></ruby>に<ruby>起<rp>(</rp><rt>お</rt><rp>)</rp></ruby>きます。', en: 'I wake up at 6 in the morning.' },
      { ja: '友達は来ません。', jaHtml: '<ruby>友達<rp>(</rp><rt>ともだち</rt><rp>)</rp></ruby>は<ruby>来<rp>(</rp><rt>き</rt><rp>)</rp></ruby>ません。', en: 'My friend is not coming.' },
      { ja: '私は映画を見ません。', jaHtml: '<ruby>私<rp>(</rp><rt>わたし</rt><rp>)</rp></ruby>は<ruby>映画<rp>(</rp><rt>えいが</rt><rp>)</rp></ruby>を<ruby>見<rp>(</rp><rt>み</rt><rp>)</rp></ruby>ません。', en: "I don't watch movies." },
      { ja: '田中さんは本を読みます。', jaHtml: '<ruby>田中<rp>(</rp><rt>たなか</rt><rp>)</rp></ruby>さんは<ruby>本<rp>(</rp><rt>ほん</rt><rp>)</rp></ruby>を<ruby>読<rp>(</rp><rt>よ</rt><rp>)</rp></ruby>みます。', en: 'Mr. Tanaka reads books.' },
      { ja: '私は毎日勉強します。', jaHtml: '<ruby>私<rp>(</rp><rt>わたし</rt><rp>)</rp></ruby>は<ruby>毎日<rp>(</rp><rt>まいにち</rt><rp>)</rp></ruby><ruby>勉強<rp>(</rp><rt>べんきょう</rt><rp>)</rp></ruby>します。', en: 'I study every day.' },
      { ja: '学生は昼ご飯を食べます。', jaHtml: '<ruby>学生<rp>(</rp><rt>がくせい</rt><rp>)</rp></ruby>は<ruby>昼<rp>(</rp><rt>ひる</rt><rp>)</rp></ruby>ご<ruby>飯<rp>(</rp><rt>はん</rt><rp>)</rp></ruby>を<ruby>食<rp>(</rp><rt>た</rt><rp>)</rp></ruby>べます。', en: 'The student eats lunch.' },
      { ja: '私は十一時に寝ます。', jaHtml: '<ruby>私<rp>(</rp><rt>わたし</rt><rp>)</rp></ruby>は<ruby>十<rp>(</rp><rt>じゅう</rt><rp>)</rp></ruby><ruby>一<rp>(</rp><rt>いち</rt><rp>)</rp></ruby><ruby>時<rp>(</rp><rt>じ</rt><rp>)</rp></ruby>に<ruby>寝<rp>(</rp><rt>ね</rt><rp>)</rp></ruby>ます。', en: 'I go to bed at 11.' },
      { ja: '明日学校に行きます。', jaHtml: '<ruby>明日<rp>(</rp><rt>あした</rt><rp>)</rp></ruby><ruby>学校<rp>(</rp><rt>がっこう</rt><rp>)</rp></ruby>に<ruby>行<rp>(</rp><rt>い</rt><rp>)</rp></ruby>きます。', en: 'I will go to school tomorrow.' },
      { ja: '週末に家に帰ります。', jaHtml: '<ruby>週末<rp>(</rp><rt>しゅうまつ</rt><rp>)</rp></ruby>に<ruby>家<rp>(</rp><rt>いえ</rt><rp>)</rp></ruby>に<ruby>帰<rp>(</rp><rt>かえ</rt><rp>)</rp></ruby>ります。', en: 'I will go home on the weekend.' },
      { ja: '音楽を聞きません。', jaHtml: '<ruby>音楽<rp>(</rp><rt>おんがく</rt><rp>)</rp></ruby>を<ruby>聞<rp>(</rp><rt>き</rt><rp>)</rp></ruby>きません。', en: "I don't listen to music." },
    ],
    4: [
      { ja: '昨日友達に会いました。', jaHtml: '<ruby>昨日<rp>(</rp><rt>きのう</rt><rp>)</rp></ruby><ruby>友達<rp>(</rp><rt>ともだち</rt><rp>)</rp></ruby>に<ruby>会<rp>(</rp><rt>あ</rt><rp>)</rp></ruby>いました。', en: 'I met a friend yesterday.' },
      { ja: '本を買いませんでした。', jaHtml: '<ruby>本<rp>(</rp><rt>ほん</rt><rp>)</rp></ruby>を<ruby>買<rp>(</rp><rt>か</rt><rp>)</rp></ruby>いませんでした。', en: "I didn't buy a book." },
      { ja: '写真を撮りました。', jaHtml: '<ruby>写真<rp>(</rp><rt>しゃしん</rt><rp>)</rp></ruby>を<ruby>撮<rp>(</rp><rt>と</rt><rp>)</rp></ruby>りました。', en: 'I took a photo.' },
      { ja: '手紙を書きました。', jaHtml: '<ruby>手紙<rp>(</rp><rt>てがみ</rt><rp>)</rp></ruby>を<ruby>書<rp>(</rp><rt>か</rt><rp>)</rp></ruby>きました。', en: 'I wrote a letter.' },
      { ja: 'バスを待ちませんでした。', jaHtml: 'バスを<ruby>待<rp>(</rp><rt>ま</rt><rp>)</rp></ruby>ちませんでした。', en: "I didn't wait for the bus." },
      { ja: '日本語が分かりました。', jaHtml: '<ruby>日本語<rp>(</rp><rt>にほんご</rt><rp>)</rp></ruby>が<ruby>分<rp>(</rp><rt>わ</rt><rp>)</rp></ruby>かりました。', en: 'I understood Japanese.' },
      { ja: '教室に猫がいました。', jaHtml: '<ruby>教室<rp>(</rp><rt>きょうしつ</rt><rp>)</rp></ruby>に<ruby>猫<rp>(</rp><rt>ねこ</rt><rp>)</rp></ruby>がいました。', en: 'There was a cat in the classroom.' },
      { ja: '机の上に本がありました。', jaHtml: '<ruby>机<rp>(</rp><rt>つくえ</rt><rp>)</rp></ruby>の<ruby>上<rp>(</rp><rt>うえ</rt><rp>)</rp></ruby>に<ruby>本<rp>(</rp><rt>ほん</rt><rp>)</rp></ruby>がありました。', en: 'There was a book on the desk.' },
      { ja: '先週新しい靴を買いました。', jaHtml: '<ruby>先週<rp>(</rp><rt>せんしゅう</rt><rp>)</rp></ruby><ruby>新<rp>(</rp><rt>あたら</rt><rp>)</rp></ruby>しい<ruby>靴<rp>(</rp><rt>くつ</rt><rp>)</rp></ruby>を<ruby>買<rp>(</rp><rt>か</rt><rp>)</rp></ruby>いました。', en: 'I bought new shoes last week.' },
      { ja: '昨日写真を撮りませんでした。', jaHtml: '<ruby>昨日<rp>(</rp><rt>きのう</rt><rp>)</rp></ruby><ruby>写真<rp>(</rp><rt>しゃしん</rt><rp>)</rp></ruby>を<ruby>撮<rp>(</rp><rt>と</rt><rp>)</rp></ruby>りませんでした。', en: "I didn't take a photo yesterday." },
    ],
    5: [
      { ja: '毎日プールで泳ぎます。', jaHtml: '<ruby>毎日<rp>(</rp><rt>まいにち</rt><rp>)</rp></ruby>プールで<ruby>泳<rp>(</rp><rt>およ</rt><rp>)</rp></ruby>ぎます。', en: 'I swim in the pool every day.' },
      { ja: '先生に聞きました。', jaHtml: '<ruby>先生<rp>(</rp><rt>せんせい</rt><rp>)</rp></ruby>に<ruby>聞<rp>(</rp><rt>き</rt><rp>)</rp></ruby>きました。', en: 'I asked the teacher.' },
      { ja: '電車に乗ります。', jaHtml: '<ruby>電車<rp>(</rp><rt>でんしゃ</rt><rp>)</rp></ruby>に<ruby>乗<rp>(</rp><rt>の</rt><rp>)</rp></ruby>ります。', en: 'I ride the train.' },
      { ja: '週末に出かけませんでした。', jaHtml: '<ruby>週末<rp>(</rp><rt>しゅうまつ</rt><rp>)</rp></ruby>に<ruby>出<rp>(</rp><rt>で</rt><rp>)</rp></ruby>かけませんでした。', en: "I didn't go out on the weekend." },
      { ja: 'スポーツをやりますか。', jaHtml: 'スポーツをやりますか。', en: 'Do you do sports?' },
      { ja: '昨日プールで泳ぎませんでした。', jaHtml: '<ruby>昨日<rp>(</rp><rt>きのう</rt><rp>)</rp></ruby>プールで<ruby>泳<rp>(</rp><rt>およ</rt><rp>)</rp></ruby>ぎませんでした。', en: "I didn't swim in the pool yesterday." },
      { ja: '友達と映画を見ました。', jaHtml: '<ruby>友達<rp>(</rp><rt>ともだち</rt><rp>)</rp></ruby>と<ruby>映画<rp>(</rp><rt>えいが</rt><rp>)</rp></ruby>を<ruby>見<rp>(</rp><rt>み</rt><rp>)</rp></ruby>ました。', en: 'I watched a movie with a friend.' },
      { ja: '先生に日本語で聞きました。', jaHtml: '<ruby>先生<rp>(</rp><rt>せんせい</rt><rp>)</rp></ruby>に<ruby>日本語<rp>(</rp><rt>にほんご</rt><rp>)</rp></ruby>で<ruby>聞<rp>(</rp><rt>き</rt><rp>)</rp></ruby>きました。', en: 'I asked the teacher in Japanese.' },
      { ja: '明日出かけます。', jaHtml: '<ruby>明日<rp>(</rp><rt>あした</rt><rp>)</rp></ruby><ruby>出<rp>(</rp><rt>で</rt><rp>)</rp></ruby>かけます。', en: 'I will go out tomorrow.' },
      { ja: '昨日電車に乗りませんでした。', jaHtml: '<ruby>昨日<rp>(</rp><rt>きのう</rt><rp>)</rp></ruby><ruby>電車<rp>(</rp><rt>でんしゃ</rt><rp>)</rp></ruby>に<ruby>乗<rp>(</rp><rt>の</rt><rp>)</rp></ruby>りませんでした。', en: "I didn't ride the train yesterday." },
    ],
    6: [
      { ja: '窓を開けてください。', jaHtml: '<ruby>窓<rp>(</rp><rt>まど</rt><rp>)</rp></ruby>を<ruby>開<rp>(</rp><rt>あ</rt><rp>)</rp></ruby>けてください。', en: 'Please open the window.' },
      { ja: 'テレビをつけてください。', jaHtml: 'テレビをつけてください。', en: 'Please turn on the TV.' },
      { ja: '友達を手伝ってください。', jaHtml: '<ruby>友達<rp>(</rp><rt>ともだち</rt><rp>)</rp></ruby>を<ruby>手伝<rp>(</rp><rt>てつだ</rt><rp>)</rp></ruby>ってください。', en: 'Please help your friend.' },
      { ja: '座ってください。', jaHtml: '<ruby>座<rp>(</rp><rt>すわ</rt><rp>)</rp></ruby>ってください。', en: 'Please sit down.' },
      { ja: '電気を消してください。', jaHtml: '<ruby>電気<rp>(</rp><rt>でんき</rt><rp>)</rp></ruby>を<ruby>消<rp>(</rp><rt>け</rt><rp>)</rp></ruby>してください。', en: 'Please turn off the light.' },
      { ja: '母に電話をかけました。', jaHtml: '<ruby>母<rp>(</rp><rt>はは</rt><rp>)</rp></ruby>に<ruby>電話<rp>(</rp><rt>でんわ</rt><rp>)</rp></ruby>をかけました。', en: 'I called my mother on the phone.' },
      { ja: '友達を連れてきました。', jaHtml: '<ruby>友達<rp>(</rp><rt>ともだち</rt><rp>)</rp></ruby>を<ruby>連<rp>(</rp><rt>つ</rt><rp>)</rp></ruby>れてきました。', en: 'I brought a friend along.' },
      { ja: 'お弁当を持ってきてください。', jaHtml: 'お<ruby>弁当<rp>(</rp><rt>べんとう</rt><rp>)</rp></ruby>を<ruby>持<rp>(</rp><rt>も</rt><rp>)</rp></ruby>ってきてください。', en: 'Please bring a lunch box.' },
      { ja: '本を借りて、家で読みました。', jaHtml: '<ruby>本<rp>(</rp><rt>ほん</rt><rp>)</rp></ruby>を<ruby>借<rp>(</rp><rt>か</rt><rp>)</rp></ruby>りて、<ruby>家<rp>(</rp><rt>いえ</rt><rp>)</rp></ruby>で<ruby>読<rp>(</rp><rt>よ</rt><rp>)</rp></ruby>みました。', en: 'I borrowed a book and read it at home.' },
      { ja: '傘を忘れました。', jaHtml: '<ruby>傘<rp>(</rp><rt>かさ</rt><rp>)</rp></ruby>を<ruby>忘<rp>(</rp><rt>わす</rt><rp>)</rp></ruby>れました。', en: 'I forgot my umbrella.' },
      { ja: '公園で遊んでください。', jaHtml: '<ruby>公園<rp>(</rp><rt>こうえん</rt><rp>)</rp></ruby>で<ruby>遊<rp>(</rp><rt>あそ</rt><rp>)</rp></ruby>んでください。', en: 'Please play in the park.' },
      { ja: '部屋に入ってもいいですか。', jaHtml: '<ruby>部屋<rp>(</rp><rt>へや</rt><rp>)</rp></ruby>に<ruby>入<rp>(</rp><rt>はい</rt><rp>)</rp></ruby>ってもいいですか。', en: 'May I enter the room?' },
    ],
    7: [
      { ja: '彼は東京に住んでいます。', jaHtml: '<ruby>彼<rp>(</rp><rt>かれ</rt><rp>)</rp></ruby>は<ruby>東京<rp>(</rp><rt>とうきょう</rt><rp>)</rp></ruby>に<ruby>住<rp>(</rp><rt>す</rt><rp>)</rp></ruby>んでいます。', en: 'He lives in Tokyo.' },
      { ja: '山田さんは帽子をかぶっています。', jaHtml: '<ruby>山田<rp>(</rp><rt>やまだ</rt><rp>)</rp></ruby>さんは<ruby>帽子<rp>(</rp><rt>ぼうし</rt><rp>)</rp></ruby>をかぶっています。', en: 'Mr. Yamada is wearing a hat.' },
      { ja: '私はメガネをかけています。', jaHtml: '<ruby>私<rp>(</rp><rt>わたし</rt><rp>)</rp></ruby>はメガネをかけています。', en: 'I wear glasses.' },
      { ja: '彼女はシャツを着ています。', jaHtml: '<ruby>彼女<rp>(</rp><rt>かのじょ</rt><rp>)</rp></ruby>はシャツを<ruby>着<rp>(</rp><rt>き</rt><rp>)</rp></ruby>ています。', en: 'She is wearing a shirt.' },
      { ja: '田中さんは会社に勤めています。', jaHtml: '<ruby>田中<rp>(</rp><rt>たなか</rt><rp>)</rp></ruby>さんは<ruby>会社<rp>(</rp><rt>かいしゃ</rt><rp>)</rp></ruby>に<ruby>勤<rp>(</rp><rt>つと</rt><rp>)</rp></ruby>めています。', en: 'Mr. Tanaka works at a company.' },
      { ja: 'あの人を知っていますか。', jaHtml: 'あの<ruby>人<rp>(</rp><rt>ひと</rt><rp>)</rp></ruby>を<ruby>知<rp>(</rp><rt>し</rt><rp>)</rp></ruby>っていますか。', en: 'Do you know that person?' },
      { ja: '友達は来年結婚します。', jaHtml: '<ruby>友達<rp>(</rp><rt>ともだち</rt><rp>)</rp></ruby>は<ruby>来年<rp>(</rp><rt>らいねん</rt><rp>)</rp></ruby><ruby>結婚<rp>(</rp><rt>けっこん</rt><rp>)</rp></ruby>します。', en: 'My friend will get married next year.' },
      { ja: '最近太りました。', jaHtml: '<ruby>最近<rp>(</rp><rt>さいきん</rt><rp>)</rp></ruby><ruby>太<rp>(</rp><rt>ふと</rt><rp>)</rp></ruby>りました。', en: 'I gained weight recently.' },
      { ja: '歌を歌いました。', jaHtml: '<ruby>歌<rp>(</rp><rt>うた</rt><rp>)</rp></ruby>を<ruby>歌<rp>(</rp><rt>うた</rt><rp>)</rp></ruby>いました。', en: 'I sang a song.' },
      { ja: '彼女は痩せています。', jaHtml: '<ruby>彼女<rp>(</rp><rt>かのじょ</rt><rp>)</rp></ruby>は<ruby>痩<rp>(</rp><rt>や</rt><rp>)</rp></ruby>せています。', en: 'She is thin.' },
    ],
    8: [
      { ja: '明日雨が降ると思います。', jaHtml: '<ruby>明日<rp>(</rp><rt>あした</rt><rp>)</rp></ruby><ruby>雨<rp>(</rp><rt>あめ</rt><rp>)</rp></ruby>が<ruby>降<rp>(</rp><rt>ふ</rt><rp>)</rp></ruby>ると<ruby>思<rp>(</rp><rt>おも</rt><rp>)</rp></ruby>います。', en: 'I think it will rain tomorrow.' },
      { ja: '晩ご飯を作らないでください。', jaHtml: '<ruby>晩<rp>(</rp><rt>ばん</rt><rp>)</rp></ruby>ご<ruby>飯<rp>(</rp><rt>はん</rt><rp>)</rp></ruby>を<ruby>作<rp>(</rp><rt>つく</rt><rp>)</rp></ruby>らないでください。', en: "Please don't make dinner." },
      { ja: 'お金が要ります。', jaHtml: 'お<ruby>金<rp>(</rp><rt>かね</rt><rp>)</rp></ruby>が<ruby>要<rp>(</rp><rt>い</rt><rp>)</rp></ruby>ります。', en: 'I need money.' },
      { ja: '今日は遅くなります。', jaHtml: '<ruby>今日<rp>(</rp><rt>きょう</rt><rp>)</rp></ruby>は<ruby>遅<rp>(</rp><rt>おそ</rt><rp>)</rp></ruby>くなります。', en: 'I will be late today.' },
      { ja: '車を運転することができます。', jaHtml: '<ruby>車<rp>(</rp><rt>くるま</rt><rp>)</rp></ruby>を<ruby>運転<rp>(</rp><rt>うんてん</rt><rp>)</rp></ruby>することができます。', en: 'I can drive a car.' },
      { ja: '皿を洗いました。', jaHtml: '<ruby>皿<rp>(</rp><rt>さら</rt><rp>)</rp></ruby>を<ruby>洗<rp>(</rp><rt>あら</rt><rp>)</rp></ruby>いました。', en: 'I washed the dishes.' },
      { ja: '「さようなら」と言いました。', jaHtml: '「さようなら」と<ruby>言<rp>(</rp><rt>い</rt><rp>)</rp></ruby>いました。', en: 'I said "goodbye."' },
      { ja: '部屋を掃除しなければなりません。', jaHtml: '<ruby>部屋<rp>(</rp><rt>へや</rt><rp>)</rp></ruby>を<ruby>掃除<rp>(</rp><rt>そうじ</rt><rp>)</rp></ruby>しなければなりません。', en: 'I have to clean the room.' },
      { ja: '服を洗濯しました。', jaHtml: '<ruby>服<rp>(</rp><rt>ふく</rt><rp>)</rp></ruby>を<ruby>洗濯<rp>(</rp><rt>せんたく</rt><rp>)</rp></ruby>しました。', en: 'I did the laundry.' },
      { ja: '紙を切ってください。', jaHtml: '<ruby>紙<rp>(</rp><rt>かみ</rt><rp>)</rp></ruby>を<ruby>切<rp>(</rp><rt>き</rt><rp>)</rp></ruby>ってください。', en: 'Please cut the paper.' },
      { ja: '料理するのが好きです。', jaHtml: '<ruby>料理<rp>(</rp><rt>りょうり</rt><rp>)</rp></ruby>するのが<ruby>好<rp>(</rp><rt>す</rt><rp>)</rp></ruby>きです。', en: 'I like to cook.' },
      { ja: '宿題を始めましょう。', jaHtml: '<ruby>宿題<rp>(</rp><rt>しゅくだい</rt><rp>)</rp></ruby>を<ruby>始<rp>(</rp><rt>はじ</rt><rp>)</rp></ruby>めましょう。', en: "Let's start the homework." },
    ],
    9: [
      { ja: 'ダンスを踊ったことがあります。', jaHtml: 'ダンスを<ruby>踊<rp>(</rp><rt>おど</rt><rp>)</rp></ruby>ったことがあります。', en: 'I have danced before.' },
      { ja: '授業が終わりました。', jaHtml: '<ruby>授業<rp>(</rp><rt>じゅぎょう</rt><rp>)</rp></ruby>が<ruby>終<rp>(</rp><rt>お</rt><rp>)</rp></ruby>わりました。', en: 'Class has ended.' },
      { ja: 'ピアノを弾いたことがありません。', jaHtml: 'ピアノを<ruby>弾<rp>(</rp><rt>ひ</rt><rp>)</rp></ruby>いたことがありません。', en: 'I have never played piano.' },
      { ja: 'プレゼントをもらいました。', jaHtml: 'プレゼントをもらいました。', en: 'I received a present.' },
      { ja: '漢字を覚えました。', jaHtml: '<ruby>漢字<rp>(</rp><rt>かんじ</rt><rp>)</rp></ruby>を<ruby>覚<rp>(</rp><rt>おぼ</rt><rp>)</rp></ruby>えました。', en: 'I memorized the kanji.' },
      { ja: '映画がまだ始まっていません。', jaHtml: '<ruby>映画<rp>(</rp><rt>えいが</rt><rp>)</rp></ruby>がまだ<ruby>始<rp>(</rp><rt>はじ</rt><rp>)</rp></ruby>まっていません。', en: "The movie hasn't started yet." },
      { ja: '毎朝運動します。', jaHtml: '<ruby>毎朝<rp>(</rp><rt>まいあさ</rt><rp>)</rp></ruby><ruby>運動<rp>(</rp><rt>うんどう</rt><rp>)</rp></ruby>します。', en: 'I exercise every morning.' },
      { ja: '公園で散歩しました。', jaHtml: '<ruby>公園<rp>(</rp><rt>こうえん</rt><rp>)</rp></ruby>で<ruby>散歩<rp>(</rp><rt>さんぽ</rt><rp>)</rp></ruby>しました。', en: 'I took a walk in the park.' },
      { ja: '授業に出なかった。', jaHtml: '<ruby>授業<rp>(</rp><rt>じゅぎょう</rt><rp>)</rp></ruby>に<ruby>出<rp>(</rp><rt>で</rt><rp>)</rp></ruby>なかった。', en: "I didn't attend class." },
      { ja: 'まだ漢字を覚えなかった。', jaHtml: 'まだ<ruby>漢字<rp>(</rp><rt>かんじ</rt><rp>)</rp></ruby>を<ruby>覚<rp>(</rp><rt>おぼ</rt><rp>)</rp></ruby>えなかった。', en: "I still didn't memorize the kanji." },
    ],
    10: [
      { ja: '東京から大阪まで三時間かかります。', jaHtml: '<ruby>東京<rp>(</rp><rt>とうきょう</rt><rp>)</rp></ruby>から<ruby>大阪<rp>(</rp><rt>おおさか</rt><rp>)</rp></ruby>まで<ruby>三<rp>(</rp><rt>さん</rt><rp>)</rp></ruby><ruby>時間<rp>(</rp><rt>じかん</rt><rp>)</rp></ruby>かかります。', en: 'It takes three hours from Tokyo to Osaka.' },
      { ja: 'ホテルに泊まりました。', jaHtml: 'ホテルに<ruby>泊<rp>(</rp><rt>と</rt><rp>)</rp></ruby>まりました。', en: 'I stayed at a hotel.' },
      { ja: '先生になりたいです。', jaHtml: '<ruby>先生<rp>(</rp><rt>せんせい</rt><rp>)</rp></ruby>になりたいです。', en: 'I want to become a teacher.' },
      { ja: 'お金を払いましたか。', jaHtml: 'お<ruby>金<rp>(</rp><rt>かね</rt><rp>)</rp></ruby>を<ruby>払<rp>(</rp><rt>はら</rt><rp>)</rp></ruby>いましたか。', en: 'Did you pay the money?' },
      { ja: 'テニスを練習しました。', jaHtml: 'テニスを<ruby>練習<rp>(</rp><rt>れんしゅう</rt><rp>)</rp></ruby>しました。', en: 'I practiced tennis.' },
      { ja: '予定を決めましょう。', jaHtml: '<ruby>予定<rp>(</rp><rt>よてい</rt><rp>)</rp></ruby>を<ruby>決<rp>(</rp><rt>き</rt><rp>)</rp></ruby>めましょう。', en: "Let's decide the plans." },
      { ja: '飛行機は電車より速いです。', jaHtml: '<ruby>飛行機<rp>(</rp><rt>ひこうき</rt><rp>)</rp></ruby>は<ruby>電車<rp>(</rp><rt>でんしゃ</rt><rp>)</rp></ruby>より<ruby>速<rp>(</rp><rt>はや</rt><rp>)</rp></ruby>いです。', en: 'Airplanes are faster than trains.' },
      { ja: 'このホテルは高くなかったです。', jaHtml: 'このホテルは<ruby>高<rp>(</rp><rt>たか</rt><rp>)</rp></ruby>くなかったです。', en: 'This hotel was not expensive.' },
      { ja: '日本に一週間泊まりました。', jaHtml: '<ruby>日本<rp>(</rp><rt>にっぽん</rt><rp>)</rp></ruby>に<ruby>一<rp>(</rp><rt>いち</rt><rp>)</rp></ruby><ruby>週間<rp>(</rp><rt>しゅうかん</rt><rp>)</rp></ruby><ruby>泊<rp>(</rp><rt>と</rt><rp>)</rp></ruby>まりました。', en: 'I stayed in Japan for one week.' },
      { ja: 'いくらかかりましたか。', jaHtml: 'いくらかかりましたか。', en: 'How much did it cost?' },
    ],
    11: [
      { ja: '日本語を習いたいです。', jaHtml: '<ruby>日本語<rp>(</rp><rt>にほんご</rt><rp>)</rp></ruby>を<ruby>習<rp>(</rp><rt>なら</rt><rp>)</rp></ruby>いたいです。', en: 'I want to learn Japanese.' },
      { ja: '山に登りたくないです。', jaHtml: '<ruby>山<rp>(</rp><rt>やま</rt><rp>)</rp></ruby>に<ruby>登<rp>(</rp><rt>のぼ</rt><rp>)</rp></ruby>りたくないです。', en: "I don't want to climb the mountain." },
      { ja: 'レストランで働いています。', jaHtml: 'レストランで<ruby>働<rp>(</rp><rt>はたら</rt><rp>)</rp></ruby>いています。', en: 'I work at a restaurant.' },
      { ja: '猫を飼っています。', jaHtml: '<ruby>猫<rp>(</rp><rt>ねこ</rt><rp>)</rp></ruby>を<ruby>飼<rp>(</rp><rt>か</rt><rp>)</rp></ruby>っています。', en: 'I own a cat.' },
      { ja: '授業をサボりました。', jaHtml: '<ruby>授業<rp>(</rp><rt>じゅぎょう</rt><rp>)</rp></ruby>をサボりました。', en: 'I skipped class.' },
      { ja: '仕事で疲れました。', jaHtml: '<ruby>仕事<rp>(</rp><rt>しごと</rt><rp>)</rp></ruby>で<ruby>疲<rp>(</rp><rt>つか</rt><rp>)</rp></ruby>れました。', en: 'I got tired from work.' },
      { ja: '仕事をやめたいです。', jaHtml: '<ruby>仕事<rp>(</rp><rt>しごと</rt><rp>)</rp></ruby>をやめたいです。', en: 'I want to quit my job.' },
      { ja: '友達を紹介しました。', jaHtml: '<ruby>友達<rp>(</rp><rt>ともだち</rt><rp>)</rp></ruby>を<ruby>紹介<rp>(</rp><rt>しょうかい</rt><rp>)</rp></ruby>しました。', en: 'I introduced a friend.' },
      { ja: '来月からダイエットします。', jaHtml: '<ruby>来月<rp>(</rp><rt>らいげつ</rt><rp>)</rp></ruby>からダイエットします。', en: 'I will go on a diet from next month.' },
      { ja: '学校に遅刻しました。', jaHtml: '<ruby>学校<rp>(</rp><rt>がっこう</rt><rp>)</rp></ruby>に<ruby>遅刻<rp>(</rp><rt>ちこく</rt><rp>)</rp></ruby>しました。', en: 'I was late for school.' },
      { ja: 'アメリカに留学したいです。', jaHtml: 'アメリカに<ruby>留学<rp>(</rp><rt>りゅうがく</rt><rp>)</rp></ruby>したいです。', en: 'I want to study abroad in America.' },
    ],
    12: [
      { ja: '夏に喉が渇きます。', jaHtml: '<ruby>夏<rp>(</rp><rt>なつ</rt><rp>)</rp></ruby>に<ruby>喉<rp>(</rp><rt>のど</rt><rp>)</rp></ruby>が<ruby>渇<rp>(</rp><rt>かわ</rt><rp>)</rp></ruby>きます。', en: 'I get thirsty in summer.' },
      { ja: '鍵をなくしてしまいました。', jaHtml: '<ruby>鍵<rp>(</rp><rt>かぎ</rt><rp>)</rp></ruby>をなくしてしまいました。', en: 'I lost my keys.' },
      { ja: '彼女と別れました。', jaHtml: '<ruby>彼女<rp>(</rp><rt>かのじょ</rt><rp>)</rp></ruby>と<ruby>別<rp>(</rp><rt>わか</rt><rp>)</rp></ruby>れました。', en: 'I broke up with my girlfriend.' },
      { ja: 'テストの前に緊張します。', jaHtml: 'テストの<ruby>前<rp>(</rp><rt>まえ</rt><rp>)</rp></ruby>に<ruby>緊張<rp>(</rp><rt>きんちょう</rt><rp>)</rp></ruby>します。', en: 'I get nervous before tests.' },
      { ja: '将来を心配しています。', jaHtml: '<ruby>将来<rp>(</rp><rt>しょうらい</rt><rp>)</rp></ruby>を<ruby>心配<rp>(</rp><rt>しんぱい</rt><rp>)</rp></ruby>しています。', en: 'I am worried about the future.' },
      { ja: '今日はとても嬉しいです。', jaHtml: '<ruby>今日<rp>(</rp><rt>きょう</rt><rp>)</rp></ruby>はとても<ruby>嬉<rp>(</rp><rt>うれ</rt><rp>)</rp></ruby>しいです。', en: 'I am very happy today.' },
      { ja: 'あの映画は悲しかったです。', jaHtml: 'あの<ruby>映画<rp>(</rp><rt>えいが</rt><rp>)</rp></ruby>は<ruby>悲<rp>(</rp><rt>かな</rt><rp>)</rp></ruby>しかったです。', en: 'That movie was sad.' },
      { ja: '頭が痛いです。', jaHtml: '<ruby>頭<rp>(</rp><rt>あたま</rt><rp>)</rp></ruby>が<ruby>痛<rp>(</rp><rt>いた</rt><rp>)</rp></ruby>いです。', en: 'I have a headache.' },
      { ja: '昨日鍵をなくしませんでした。', jaHtml: '<ruby>昨日<rp>(</rp><rt>きのう</rt><rp>)</rp></ruby><ruby>鍵<rp>(</rp><rt>かぎ</rt><rp>)</rp></ruby>をなくしませんでした。', en: "I didn't lose my keys yesterday." },
      { ja: '緊張しないでください。', jaHtml: '<ruby>緊張<rp>(</rp><rt>きんちょう</rt><rp>)</rp></ruby>しないでください。', en: "Please don't be nervous." },
    ],
    13: [
      { ja: 'セーターを編むことができます。', jaHtml: 'セーターを<ruby>編<rp>(</rp><rt>あ</rt><rp>)</rp></ruby>むことができます。', en: 'I can knit a sweater.' },
      { ja: 'お金を貸してください。', jaHtml: 'お<ruby>金<rp>(</rp><rt>かね</rt><rp>)</rp></ruby>を<ruby>貸<rp>(</rp><rt>か</rt><rp>)</rp></ruby>してください。', en: 'Please lend me money.' },
      { ja: '試験のために頑張ります。', jaHtml: '<ruby>試験<rp>(</rp><rt>しけん</rt><rp>)</rp></ruby>のために<ruby>頑張<rp>(</rp><rt>がんば</rt><rp>)</rp></ruby>ります。', en: 'I will do my best for the exam.' },
      { ja: '映画を見て泣きました。', jaHtml: '<ruby>映画<rp>(</rp><rt>えいが</rt><rp>)</rp></ruby>を<ruby>見<rp>(</rp><rt>み</rt><rp>)</rp></ruby>て<ruby>泣<rp>(</rp><rt>な</rt><rp>)</rp></ruby>きました。', en: 'I cried watching a movie.' },
      { ja: '歯を磨いてください。', jaHtml: '<ruby>歯<rp>(</rp><rt>は</rt><rp>)</rp></ruby>を<ruby>磨<rp>(</rp><rt>みが</rt><rp>)</rp></ruby>いてください。', en: 'Please brush your teeth.' },
      { ja: '約束を守らなければなりません。', jaHtml: '<ruby>約束<rp>(</rp><rt>やくそく</rt><rp>)</rp></ruby>を<ruby>守<rp>(</rp><rt>まも</rt><rp>)</rp></ruby>らなければなりません。', en: 'You must keep your promise.' },
      { ja: 'この映画に感動しました。', jaHtml: 'この<ruby>映画<rp>(</rp><rt>えいが</rt><rp>)</rp></ruby>に<ruby>感動<rp>(</rp><rt>かんどう</rt><rp>)</rp></ruby>しました。', en: 'I was moved by this movie.' },
      { ja: 'ピアノが弾けます。', jaHtml: 'ピアノが<ruby>弾<rp>(</rp><rt>ひ</rt><rp>)</rp></ruby>けます。', en: 'I can play piano.' },
      { ja: '日本語が話せるようになりました。', jaHtml: '<ruby>日本語<rp>(</rp><rt>にほんご</rt><rp>)</rp></ruby>が<ruby>話<rp>(</rp><rt>はな</rt><rp>)</rp></ruby>せるようになりました。', en: 'I became able to speak Japanese.' },
      { ja: '漢字が読めません。', jaHtml: '<ruby>漢字<rp>(</rp><rt>かんじ</rt><rp>)</rp></ruby>が<ruby>読<rp>(</rp><rt>よ</rt><rp>)</rp></ruby>めません。', en: "I can't read kanji." },
    ],
    14: [
      { ja: '友達に荷物を送りました。', jaHtml: '<ruby>友達<rp>(</rp><rt>ともだち</rt><rp>)</rp></ruby>に<ruby>荷物<rp>(</rp><rt>にもつ</rt><rp>)</rp></ruby>を<ruby>送<rp>(</rp><rt>おく</rt><rp>)</rp></ruby>りました。', en: 'I sent a package to a friend.' },
      { ja: 'この服は私に似合いますか。', jaHtml: 'この<ruby>服<rp>(</rp><rt>ふく</rt><rp>)</rp></ruby>は<ruby>私<rp>(</rp><rt>わたし</rt><rp>)</rp></ruby>に<ruby>似合<rp>(</rp><rt>にあ</rt><rp>)</rp></ruby>いますか。', en: 'Does this outfit suit me?' },
      { ja: '夢を諦めないでください。', jaHtml: '<ruby>夢<rp>(</rp><rt>ゆめ</rt><rp>)</rp></ruby>を<ruby>諦<rp>(</rp><rt>あきら</rt><rp>)</rp></ruby>めないでください。', en: "Please don't give up on your dream." },
      { ja: '彼女にプレゼントをあげました。', jaHtml: '<ruby>彼女<rp>(</rp><rt>かのじょ</rt><rp>)</rp></ruby>にプレゼントをあげました。', en: 'I gave a present to my girlfriend.' },
      { ja: '友達が本をくれました。', jaHtml: '<ruby>友達<rp>(</rp><rt>ともだち</rt><rp>)</rp></ruby>が<ruby>本<rp>(</rp><rt>ほん</rt><rp>)</rp></ruby>をくれました。', en: 'A friend gave me a book.' },
      { ja: '日本語ができるようになりました。', jaHtml: '<ruby>日本語<rp>(</rp><rt>にほんご</rt><rp>)</rp></ruby>ができるようになりました。', en: 'I became able to do Japanese.' },
      { ja: '先生に相談しました。', jaHtml: '<ruby>先生<rp>(</rp><rt>せんせい</rt><rp>)</rp></ruby>に<ruby>相談<rp>(</rp><rt>そうだん</rt><rp>)</rp></ruby>しました。', en: 'I consulted the teacher.' },
      { ja: '母にセーターを編んであげました。', jaHtml: '<ruby>母<rp>(</rp><rt>はは</rt><rp>)</rp></ruby>にセーターを<ruby>編<rp>(</rp><rt>あ</rt><rp>)</rp></ruby>んであげました。', en: 'I knitted a sweater for my mother.' },
      { ja: '兄がカメラを貸してくれました。', jaHtml: '<ruby>兄<rp>(</rp><rt>あに</rt><rp>)</rp></ruby>がカメラを<ruby>貸<rp>(</rp><rt>か</rt><rp>)</rp></ruby>してくれました。', en: 'My older brother lent me a camera.' },
      { ja: '友達にお金をあげたくないです。', jaHtml: '<ruby>友達<rp>(</rp><rt>ともだち</rt><rp>)</rp></ruby>にお<ruby>金<rp>(</rp><rt>かね</rt><rp>)</rp></ruby>をあげたくないです。', en: "I don't want to give money to a friend." },
    ],
    15: [
      { ja: '車を売りました。', jaHtml: '<ruby>車<rp>(</rp><rt>くるま</rt><rp>)</rp></ruby>を<ruby>売<rp>(</rp><rt>う</rt><rp>)</rp></ruby>りました。', en: 'I sold the car.' },
      { ja: '銀行でお金を下ろしました。', jaHtml: '<ruby>銀行<rp>(</rp><rt>ぎんこう</rt><rp>)</rp></ruby>でお<ruby>金<rp>(</rp><rt>かね</rt><rp>)</rp></ruby>を<ruby>下<rp>(</rp><rt>お</rt><rp>)</rp></ruby>ろしました。', en: 'I withdrew money at the bank.' },
      { ja: '絵を描くのが好きです。', jaHtml: '<ruby>絵<rp>(</rp><rt>え</rt><rp>)</rp></ruby>を<ruby>描<rp>(</rp><rt>えが</rt><rp>)</rp></ruby>くのが<ruby>好<rp>(</rp><rt>す</rt><rp>)</rp></ruby>きです。', en: 'I like drawing pictures.' },
      { ja: '仕事を探しています。', jaHtml: '<ruby>仕事<rp>(</rp><rt>しごと</rt><rp>)</rp></ruby>を<ruby>探<rp>(</rp><rt>さが</rt><rp>)</rp></ruby>しています。', en: 'I am looking for a job.' },
      { ja: '友達を映画に誘いました。', jaHtml: '<ruby>友達<rp>(</rp><rt>ともだち</rt><rp>)</rp></ruby>を<ruby>映画<rp>(</rp><rt>えいが</rt><rp>)</rp></ruby>に<ruby>誘<rp>(</rp><rt>さそ</rt><rp>)</rp></ruby>いました。', en: 'I invited a friend to a movie.' },
      { ja: '電話でしゃべりました。', jaHtml: '<ruby>電話<rp>(</rp><rt>でんわ</rt><rp>)</rp></ruby>でしゃべりました。', en: 'I chatted on the phone.' },
      { ja: '駅に着いたら電話してください。', jaHtml: '<ruby>駅<rp>(</rp><rt>えき</rt><rp>)</rp></ruby>に<ruby>着<rp>(</rp><rt>つ</rt><rp>)</rp></ruby>いたら<ruby>電話<rp>(</rp><rt>でんわ</rt><rp>)</rp></ruby>してください。', en: 'When you arrive at the station, please call.' },
      { ja: '車に気をつけてください。', jaHtml: '<ruby>車<rp>(</rp><rt>くるま</rt><rp>)</rp></ruby>に<ruby>気<rp>(</rp><rt>き</rt><rp>)</rp></ruby>をつけてください。', en: 'Please be careful of cars.' },
      { ja: '京都を観光しましょう。', jaHtml: '<ruby>京都<rp>(</rp><rt>きょうと</rt><rp>)</rp></ruby>を<ruby>観光<rp>(</rp><rt>かんこう</rt><rp>)</rp></ruby>しましょう。', en: "Let's sightsee in Kyoto." },
      { ja: '大学を卒業しました。', jaHtml: '<ruby>大学<rp>(</rp><rt>だいがく</rt><rp>)</rp></ruby>を<ruby>卒業<rp>(</rp><rt>そつぎょう</rt><rp>)</rp></ruby>しました。', en: 'I graduated from university.' },
      { ja: 'レストランを予約しました。', jaHtml: 'レストランを<ruby>予約<rp>(</rp><rt>よやく</rt><rp>)</rp></ruby>しました。', en: 'I reserved a restaurant.' },
      { ja: '窓から山が見えます。', jaHtml: '<ruby>窓<rp>(</rp><rt>まど</rt><rp>)</rp></ruby>から<ruby>山<rp>(</rp><rt>やま</rt><rp>)</rp></ruby>が<ruby>見<rp>(</rp><rt>み</rt><rp>)</rp></ruby>えます。', en: 'I can see the mountain from the window.' },
    ],
    16: [
      { ja: '弟を起こしてください。', jaHtml: '<ruby>弟<rp>(</rp><rt>おとうと</rt><rp>)</rp></ruby>を<ruby>起<rp>(</rp><rt>お</rt><rp>)</rp></ruby>こしてください。', en: 'Please wake up my younger brother.' },
      { ja: '友達に昼ご飯をおごりました。', jaHtml: '<ruby>友達<rp>(</rp><rt>ともだち</rt><rp>)</rp></ruby>に<ruby>昼<rp>(</rp><rt>ひる</rt><rp>)</rp></ruby>ご<ruby>飯<rp>(</rp><rt>はん</rt><rp>)</rp></ruby>をおごりました。', en: 'I treated my friend to lunch.' },
      { ja: '最近落ち込んでいます。', jaHtml: '<ruby>最近<rp>(</rp><rt>さいきん</rt><rp>)</rp></ruby><ruby>落<rp>(</rp><rt>お</rt><rp>)</rp></ruby>ち<ruby>込<rp>(</rp><rt>こ</rt><rp>)</rp></ruby>んでいます。', en: 'I have been feeling depressed recently.' },
      { ja: 'お金に困っています。', jaHtml: 'お<ruby>金<rp>(</rp><rt>かね</rt><rp>)</rp></ruby>に<ruby>困<rp>(</rp><rt>こま</rt><rp>)</rp></ruby>っています。', en: 'I am in trouble about money.' },
      { ja: '宿題を出してください。', jaHtml: '<ruby>宿題<rp>(</rp><rt>しゅくだい</rt><rp>)</rp></ruby>を<ruby>出<rp>(</rp><rt>だ</rt><rp>)</rp></ruby>してください。', en: 'Please submit your homework.' },
      { ja: 'パソコンを直しました。', jaHtml: 'パソコンを<ruby>直<rp>(</rp><rt>なお</rt><rp>)</rp></ruby>しました。', en: 'I fixed the computer.' },
      { ja: '鍵が見つかりました。', jaHtml: '<ruby>鍵<rp>(</rp><rt>かぎ</rt><rp>)</rp></ruby>が<ruby>見<rp>(</rp><rt>み</rt><rp>)</rp></ruby>つかりました。', en: 'The keys were found.' },
      { ja: 'この文を英語に訳してください。', jaHtml: 'この<ruby>文<rp>(</rp><rt>ぶん</rt><rp>)</rp></ruby>を<ruby>英語<rp>(</rp><rt>えいご</rt><rp>)</rp></ruby>に<ruby>訳<rp>(</rp><rt>やく</rt><rp>)</rp></ruby>してください。', en: 'Please translate this sentence into English.' },
      { ja: '冗談を聞いて笑いました。', jaHtml: '<ruby>冗談<rp>(</rp><rt>じょうだん</rt><rp>)</rp></ruby>を<ruby>聞<rp>(</rp><rt>き</rt><rp>)</rp></ruby>いて<ruby>笑<rp>(</rp><rt>わら</rt><rp>)</rp></ruby>いました。', en: 'I laughed after hearing a joke.' },
      { ja: '電車に乗り遅れてしまいました。', jaHtml: '<ruby>電車<rp>(</rp><rt>でんしゃ</rt><rp>)</rp></ruby>に<ruby>乗<rp>(</rp><rt>の</rt><rp>)</rp></ruby>り<ruby>遅<rp>(</rp><rt>おく</rt><rp>)</rp></ruby>れてしまいました。', en: 'I missed the train.' },
      { ja: '写真を見せてください。', jaHtml: '<ruby>写真<rp>(</rp><rt>しゃしん</rt><rp>)</rp></ruby>を<ruby>見<rp>(</rp><rt>み</rt><rp>)</rp></ruby>せてください。', en: 'Please show me the photo.' },
      { ja: '日曜日に朝寝坊しました。', jaHtml: '<ruby>日曜日<rp>(</rp><rt>にちようび</rt><rp>)</rp></ruby>に<ruby>朝寝坊<rp>(</rp><rt>あさねぼう</rt><rp>)</rp></ruby>しました。', en: 'I overslept on Sunday.' },
    ],
    17: [
      { ja: 'プレゼントを選んでいます。', jaHtml: 'プレゼントを<ruby>選<rp>(</rp><rt>えら</rt><rp>)</rp></ruby>んでいます。', en: 'I am choosing a present.' },
      { ja: '電車が込んでいます。', jaHtml: '<ruby>電車<rp>(</rp><rt>でんしゃ</rt><rp>)</rp></ruby>が<ruby>込<rp>(</rp><rt>こ</rt><rp>)</rp></ruby>んでいます。', en: 'The train is crowded.' },
      { ja: '靴を脱いでください。', jaHtml: '<ruby>靴<rp>(</rp><rt>くつ</rt><rp>)</rp></ruby>を<ruby>脱<rp>(</rp><rt>ぬ</rt><rp>)</rp></ruby>いでください。', en: 'Please take off your shoes.' },
      { ja: '東京で生まれました。', jaHtml: '<ruby>東京<rp>(</rp><rt>とうきょう</rt><rp>)</rp></ruby>で<ruby>生<rp>(</rp><rt>う</rt><rp>)</rp></ruby>まれました。', en: 'I was born in Tokyo.' },
      { ja: 'お金が足りません。', jaHtml: 'お<ruby>金<rp>(</rp><rt>かね</rt><rp>)</rp></ruby>が<ruby>足<rp>(</rp><rt>た</rt><rp>)</rp></ruby>りません。', en: "There isn't enough money." },
      { ja: '日本の生活に慣れました。', jaHtml: '<ruby>日本<rp>(</rp><rt>にっぽん</rt><rp>)</rp></ruby>の<ruby>生活<rp>(</rp><rt>せいかつ</rt><rp>)</rp></ruby>に<ruby>慣<rp>(</rp><rt>な</rt><rp>)</rp></ruby>れました。', en: 'I got used to life in Japan.' },
      { ja: '毎朝化粧します。', jaHtml: '<ruby>毎朝<rp>(</rp><rt>まいあさ</rt><rp>)</rp></ruby><ruby>化粧<rp>(</rp><rt>けしょう</rt><rp>)</rp></ruby>します。', en: 'I put on makeup every morning.' },
      { ja: '来年就職したいです。', jaHtml: '<ruby>来年<rp>(</rp><rt>らいねん</rt><rp>)</rp></ruby><ruby>就職<rp>(</rp><rt>しゅうしょく</rt><rp>)</rp></ruby>したいです。', en: 'I want to get a job next year.' },
      { ja: 'もっと勉強すればよかったです。', jaHtml: 'もっと<ruby>勉強<rp>(</rp><rt>べんきょう</rt><rp>)</rp></ruby>すればよかったです。', en: 'I wish I had studied more.' },
      { ja: '早く寝れば元気になります。', jaHtml: '<ruby>早<rp>(</rp><rt>はや</rt><rp>)</rp></ruby>く<ruby>寝<rp>(</rp><rt>ね</rt><rp>)</rp></ruby>れば<ruby>元気<rp>(</rp><rt>げんき</rt><rp>)</rp></ruby>になります。', en: "If you go to bed early, you'll feel better." },
    ],
    18: [
      { ja: 'ドアが開きました。', jaHtml: 'ドアが<ruby>開<rp>(</rp><rt>ひら</rt><rp>)</rp></ruby>きました。', en: 'The door opened.' },
      { ja: '先生に謝りました。', jaHtml: '<ruby>先生<rp>(</rp><rt>せんせい</rt><rp>)</rp></ruby>に<ruby>謝<rp>(</rp><rt>あやま</rt><rp>)</rp></ruby>りました。', en: 'I apologized to the teacher.' },
      { ja: 'ボタンを押してください。', jaHtml: 'ボタンを<ruby>押<rp>(</rp><rt>お</rt><rp>)</rp></ruby>してください。', en: 'Please press the button.' },
      { ja: '財布を落としてしまいました。', jaHtml: '<ruby>財布<rp>(</rp><rt>さいふ</rt><rp>)</rp></ruby>を<ruby>落<rp>(</rp><rt>お</rt><rp>)</rp></ruby>としてしまいました。', en: 'I dropped my wallet.' },
      { ja: '道で転びました。', jaHtml: '<ruby>道<rp>(</rp><rt>みち</rt><rp>)</rp></ruby>で<ruby>転<rp>(</rp><rt>ころ</rt><rp>)</rp></ruby>びました。', en: 'I fell on the road.' },
      { ja: 'おもちゃを壊さないでください。', jaHtml: 'おもちゃを<ruby>壊<rp>(</rp><rt>こわ</rt><rp>)</rp></ruby>さないでください。', en: "Please don't break the toy." },
      { ja: '桜が咲いています。', jaHtml: '<ruby>桜<rp>(</rp><rt>さくら</rt><rp>)</rp></ruby>が<ruby>咲<rp>(</rp><rt>さ</rt><rp>)</rp></ruby>いています。', en: 'The cherry blossoms are blooming.' },
      { ja: '店が閉まりました。', jaHtml: '<ruby>店<rp>(</rp><rt>みせ</rt><rp>)</rp></ruby>が<ruby>閉<rp>(</rp><rt>し</rt><rp>)</rp></ruby>まりました。', en: 'The shop closed.' },
      { ja: 'パソコンが壊れてしまいました。', jaHtml: 'パソコンが<ruby>壊<rp>(</rp><rt>こわ</rt><rp>)</rp></ruby>れてしまいました。', en: 'The computer broke.' },
      { ja: '部屋を片付けてください。', jaHtml: '<ruby>部屋<rp>(</rp><rt>へや</rt><rp>)</rp></ruby>を<ruby>片付<rp>(</rp><rt>かたづ</rt><rp>)</rp></ruby>けてください。', en: 'Please tidy up the room.' },
      { ja: '将来のことを考えています。', jaHtml: '<ruby>将来<rp>(</rp><rt>しょうらい</rt><rp>)</rp></ruby>のことを<ruby>考<rp>(</rp><rt>かんが</rt><rp>)</rp></ruby>えています。', en: 'I am thinking about the future.' },
      { ja: 'ピザを注文しましょう。', jaHtml: 'ピザを<ruby>注文<rp>(</rp><rt>ちゅうもん</rt><rp>)</rp></ruby>しましょう。', en: "Let's order pizza." },
    ],
    19: [
      { ja: '先生はもういらっしゃいますか。', jaHtml: '<ruby>先生<rp>(</rp><rt>せんせい</rt><rp>)</rp></ruby>はもういらっしゃいますか。', en: 'Is the teacher here already? (honorific)' },
      { ja: '母が怒りました。', jaHtml: '<ruby>母<rp>(</rp><rt>はは</rt><rp>)</rp></ruby>が<ruby>怒<rp>(</rp><rt>おこ</rt><rp>)</rp></ruby>りました。', en: 'Mom got angry.' },
      { ja: '先生がおっしゃいました。', jaHtml: '<ruby>先生<rp>(</rp><rt>せんせい</rt><rp>)</rp></ruby>がおっしゃいました。', en: 'The teacher said. (honorific)' },
      { ja: '予定が決まりました。', jaHtml: '<ruby>予定<rp>(</rp><rt>よてい</rt><rp>)</rp></ruby>が<ruby>決<rp>(</rp><rt>き</rt><rp>)</rp></ruby>まりました。', en: 'The plans have been decided.' },
      { ja: '先生がお菓子を下さいました。', jaHtml: '<ruby>先生<rp>(</rp><rt>せんせい</rt><rp>)</rp></ruby>がお<ruby>菓子<rp>(</rp><rt>かし</rt><rp>)</rp></ruby>を<ruby>下<rp>(</rp><rt>くだ</rt><rp>)</rp></ruby>さいました。', en: 'The teacher gave us sweets. (honorific)' },
      { ja: '大阪に引っ越しました。', jaHtml: '<ruby>大阪<rp>(</rp><rt>おおさか</rt><rp>)</rp></ruby>に<ruby>引<rp>(</rp><rt>ひ</rt><rp>)</rp></ruby>っ<ruby>越<rp>(</rp><rt>こ</rt><rp>)</rp></ruby>しました。', en: 'I moved to Osaka.' },
      { ja: 'タクシーを呼んでください。', jaHtml: 'タクシーを<ruby>呼<rp>(</rp><rt>よ</rt><rp>)</rp></ruby>んでください。', en: 'Please call a taxi.' },
      { ja: 'コンビニに寄りましょう。', jaHtml: 'コンビニに<ruby>寄<rp>(</rp><rt>よ</rt><rp>)</rp></ruby>りましょう。', en: "Let's stop by the convenience store." },
      { ja: '電車が遅れています。', jaHtml: '<ruby>電車<rp>(</rp><rt>でんしゃ</rt><rp>)</rp></ruby>が<ruby>遅<rp>(</rp><rt>おく</rt><rp>)</rp></ruby>れています。', en: 'The train is delayed.' },
      { ja: 'パーティーに招待されました。', jaHtml: 'パーティーに<ruby>招待<rp>(</rp><rt>しょうたい</rt><rp>)</rp></ruby>されました。', en: 'I was invited to a party.' },
    ],
    20: [
      { ja: '私がお手伝いを致します。', jaHtml: '<ruby>私<rp>(</rp><rt>わたし</rt><rp>)</rp></ruby>がお<ruby>手伝<rp>(</rp><rt>てつだ</rt><rp>)</rp></ruby>いを<ruby>致<rp>(</rp><rt>いた</rt><rp>)</rp></ruby>します。', en: 'I will help you. (humble)' },
      { ja: 'お土産を頂きました。', jaHtml: 'お<ruby>土産<rp>(</rp><rt>みやげ</rt><rp>)</rp></ruby>を<ruby>頂<rp>(</rp><rt>いただ</rt><rp>)</rp></ruby>きました。', en: 'I received a souvenir. (humble)' },
      { ja: '先生のお宅に伺いました。', jaHtml: '<ruby>先生<rp>(</rp><rt>せんせい</rt><rp>)</rp></ruby>のお<ruby>宅<rp>(</rp><rt>たく</rt><rp>)</rp></ruby>に<ruby>伺<rp>(</rp><rt>うかが</rt><rp>)</rp></ruby>いました。', en: "I visited the teacher's home. (humble)" },
      { ja: '私はこちらにおります。', jaHtml: '<ruby>私<rp>(</rp><rt>わたし</rt><rp>)</rp></ruby>はこちらにおります。', en: 'I am here. (humble)' },
      { ja: 'すぐに参ります。', jaHtml: 'すぐに<ruby>参<rp>(</rp><rt>まい</rt><rp>)</rp></ruby>ります。', en: 'I will come right away. (humble)' },
      { ja: '次の角を右に曲がってください。', jaHtml: '<ruby>次<rp>(</rp><rt>つぎ</rt><rp>)</rp></ruby>の<ruby>角<rp>(</rp><rt>かく</rt><rp>)</rp></ruby>を<ruby>右<rp>(</rp><rt>みぎ</rt><rp>)</rp></ruby>に<ruby>曲<rp>(</rp><rt>ま</rt><rp>)</rp></ruby>がってください。', en: 'Please turn right at the next corner.' },
      { ja: '田中と申します。', jaHtml: '<ruby>田中<rp>(</rp><rt>たなか</rt><rp>)</rp></ruby>と<ruby>申<rp>(</rp><rt>もう</rt><rp>)</rp></ruby>します。', en: 'My name is Tanaka. (humble)' },
      { ja: '家に戻りました。', jaHtml: '<ruby>家<rp>(</rp><rt>いえ</rt><rp>)</rp></ruby>に<ruby>戻<rp>(</rp><rt>もど</rt><rp>)</rp></ruby>りました。', en: 'I returned home.' },
      { ja: '音楽が聞こえますか。', jaHtml: '<ruby>音楽<rp>(</rp><rt>おんがく</rt><rp>)</rp></ruby>が<ruby>聞<rp>(</rp><rt>き</rt><rp>)</rp></ruby>こえますか。', en: 'Can you hear the music?' },
      { ja: 'メッセージを伝えてください。', jaHtml: 'メッセージを<ruby>伝<rp>(</rp><rt>つた</rt><rp>)</rp></ruby>えてください。', en: 'Please convey the message.' },
      { ja: '電話番号を交換しましょう。', jaHtml: '<ruby>電話<rp>(</rp><rt>でんわ</rt><rp>)</rp></ruby><ruby>番号<rp>(</rp><rt>ばんごう</rt><rp>)</rp></ruby>を<ruby>交換<rp>(</rp><rt>こうかん</rt><rp>)</rp></ruby>しましょう。', en: "Let's exchange phone numbers." },
    ],
    21: [
      { ja: '財布を盗まれました。', jaHtml: '<ruby>財布<rp>(</rp><rt>さいふ</rt><rp>)</rp></ruby>を<ruby>盗<rp>(</rp><rt>ぬす</rt><rp>)</rp></ruby>まれました。', en: 'My wallet was stolen.' },
      { ja: '先生に褒められました。', jaHtml: '<ruby>先生<rp>(</rp><rt>せんせい</rt><rp>)</rp></ruby>に<ruby>褒<rp>(</rp><rt>ほ</rt><rp>)</rp></ruby>められました。', en: 'I was praised by the teacher.' },
      { ja: '電車で足を踏まれました。', jaHtml: '<ruby>電車<rp>(</rp><rt>でんしゃ</rt><rp>)</rp></ruby>で<ruby>足<rp>(</rp><rt>あし</rt><rp>)</rp></ruby>を<ruby>踏<rp>(</rp><rt>ふ</rt><rp>)</rp></ruby>まれました。', en: 'My foot was stepped on in the train.' },
      { ja: '友達にケーキを焼いてあげました。', jaHtml: '<ruby>友達<rp>(</rp><rt>ともだち</rt><rp>)</rp></ruby>にケーキを<ruby>焼<rp>(</rp><rt>や</rt><rp>)</rp></ruby>いてあげました。', en: 'I baked a cake for my friend.' },
      { ja: 'お金をためています。', jaHtml: 'お<ruby>金<rp>(</rp><rt>かね</rt><rp>)</rp></ruby>をためています。', en: 'I am saving money.' },
      { ja: '勉強を続けてください。', jaHtml: '<ruby>勉強<rp>(</rp><rt>べんきょう</rt><rp>)</rp></ruby>を<ruby>続<rp>(</rp><rt>つづ</rt><rp>)</rp></ruby>けてください。', en: 'Please continue studying.' },
      { ja: '答えを間違えました。', jaHtml: '<ruby>答<rp>(</rp><rt>こた</rt><rp>)</rp></ruby>えを<ruby>間違<rp>(</rp><rt>まちが</rt><rp>)</rp></ruby>えました。', en: 'I made a mistake on the answer.' },
      { ja: '財布を見つけました。', jaHtml: '<ruby>財布<rp>(</rp><rt>さいふ</rt><rp>)</rp></ruby>を<ruby>見<rp>(</rp><rt>み</rt><rp>)</rp></ruby>つけました。', en: 'I found a wallet.' },
      { ja: '友達に連絡しました。', jaHtml: '<ruby>友達<rp>(</rp><rt>ともだち</rt><rp>)</rp></ruby>に<ruby>連絡<rp>(</rp><rt>れんらく</rt><rp>)</rp></ruby>しました。', en: 'I contacted my friend.' },
      { ja: 'ポスターを壁に貼りました。', jaHtml: 'ポスターを<ruby>壁<rp>(</rp><rt>かべ</rt><rp>)</rp></ruby>に<ruby>貼<rp>(</rp><rt>は</rt><rp>)</rp></ruby>りました。', en: 'I put a poster on the wall.' },
      { ja: 'プレゼントを包んでください。', jaHtml: 'プレゼントを<ruby>包<rp>(</rp><rt>つつ</rt><rp>)</rp></ruby>んでください。', en: 'Please wrap the present.' },
    ],
    22: [
      { ja: '試合に勝ちました。', jaHtml: '<ruby>試合<rp>(</rp><rt>しあい</rt><rp>)</rp></ruby>に<ruby>勝<rp>(</rp><rt>か</rt><rp>)</rp></ruby>ちました。', en: 'I won the game.' },
      { ja: '公園で走りました。', jaHtml: '<ruby>公園<rp>(</rp><rt>こうえん</rt><rp>)</rp></ruby>で<ruby>走<rp>(</rp><rt>はし</rt><rp>)</rp></ruby>りました。', en: 'I ran in the park.' },
      { ja: '荷物を運んでください。', jaHtml: '<ruby>荷物<rp>(</rp><rt>にもつ</rt><rp>)</rp></ruby>を<ruby>運<rp>(</rp><rt>はこ</rt><rp>)</rp></ruby>んでください。', en: 'Please carry the luggage.' },
      { ja: 'ゴミを拾いました。', jaHtml: 'ゴミを<ruby>拾<rp>(</rp><rt>ひろ</rt><rp>)</rp></ruby>いました。', en: 'I picked up trash.' },
      { ja: '電車に間に合いました。', jaHtml: '<ruby>電車<rp>(</rp><rt>でんしゃ</rt><rp>)</rp></ruby>に<ruby>間<rp>(</rp><rt>ま</rt><rp>)</rp></ruby>に<ruby>合<rp>(</rp><rt>あ</rt><rp>)</rp></ruby>いました。', en: 'I made it on time for the train.' },
      { ja: '母は私に野菜を食べさせました。', jaHtml: '<ruby>母<rp>(</rp><rt>はは</rt><rp>)</rp></ruby>は<ruby>私<rp>(</rp><rt>わたし</rt><rp>)</rp></ruby>に<ruby>野菜<rp>(</rp><rt>やさい</rt><rp>)</rp></ruby>を<ruby>食<rp>(</rp><rt>た</rt><rp>)</rp></ruby>べさせました。', en: 'Mom made me eat vegetables.' },
      { ja: '先生は学生に作文を書かせました。', jaHtml: '<ruby>先生<rp>(</rp><rt>せんせい</rt><rp>)</rp></ruby>は<ruby>学生<rp>(</rp><rt>がくせい</rt><rp>)</rp></ruby>に<ruby>作文<rp>(</rp><rt>さくぶん</rt><rp>)</rp></ruby>を<ruby>書<rp>(</rp><rt>か</rt><rp>)</rp></ruby>かせました。', en: 'The teacher made the students write an essay.' },
      { ja: '子供を一人で育てています。', jaHtml: '<ruby>子供<rp>(</rp><rt>こども</rt><rp>)</rp></ruby>を<ruby>一<rp>(</rp><rt>いち</rt><rp>)</rp></ruby><ruby>人<rp>(</rp><rt>にん</rt><rp>)</rp></ruby>で<ruby>育<rp>(</rp><rt>そだ</rt><rp>)</rp></ruby>てています。', en: 'I am raising a child by myself.' },
      { ja: '試合に負けてしまいました。', jaHtml: '<ruby>試合<rp>(</rp><rt>しあい</rt><rp>)</rp></ruby>に<ruby>負<rp>(</rp><rt>ま</rt><rp>)</rp></ruby>けてしまいました。', en: 'I lost the game.' },
      { ja: 'この意見に賛成します。', jaHtml: 'この<ruby>意見<rp>(</rp><rt>いけん</rt><rp>)</rp></ruby>に<ruby>賛成<rp>(</rp><rt>さんせい</rt><rp>)</rp></ruby>します。', en: 'I agree with this opinion.' },
      { ja: 'その計画に反対します。', jaHtml: 'その<ruby>計画<rp>(</rp><rt>けいかく</rt><rp>)</rp></ruby>に<ruby>反対<rp>(</rp><rt>はんたい</rt><rp>)</rp></ruby>します。', en: 'I oppose that plan.' },
    ],
    23: [
      { ja: '先生に毎日漢字を書かせられます。', jaHtml: '<ruby>先生<rp>(</rp><rt>せんせい</rt><rp>)</rp></ruby>に<ruby>毎日<rp>(</rp><rt>まいにち</rt><rp>)</rp></ruby><ruby>漢字<rp>(</rp><rt>かんじ</rt><rp>)</rp></ruby>を<ruby>書<rp>(</rp><rt>か</rt><rp>)</rp></ruby>かせられます。', en: 'I am made to write kanji every day by the teacher.' },
      { ja: '親に野菜を食べさせられました。', jaHtml: '<ruby>親<rp>(</rp><rt>おや</rt><rp>)</rp></ruby>に<ruby>野菜<rp>(</rp><rt>やさい</rt><rp>)</rp></ruby>を<ruby>食<rp>(</rp><rt>た</rt><rp>)</rp></ruby>べさせられました。', en: 'I was made to eat vegetables by my parents.' },
      { ja: '試験を受けました。', jaHtml: '<ruby>試験<rp>(</rp><rt>しけん</rt><rp>)</rp></ruby>を<ruby>受<rp>(</rp><rt>う</rt><rp>)</rp></ruby>けました。', en: 'I took an exam.' },
      { ja: '質問に答えてください。', jaHtml: '<ruby>質問<rp>(</rp><rt>しつもん</rt><rp>)</rp></ruby>に<ruby>答<rp>(</rp><rt>こた</rt><rp>)</rp></ruby>えてください。', en: 'Please answer the question.' },
      { ja: '家から離れたくないです。', jaHtml: '<ruby>家<rp>(</rp><rt>いえ</rt><rp>)</rp></ruby>から<ruby>離<rp>(</rp><rt>はな</rt><rp>)</rp></ruby>れたくないです。', en: "I don't want to be away from home." },
      { ja: '痛みを我慢しました。', jaHtml: '<ruby>痛<rp>(</rp><rt>いた</rt><rp>)</rp></ruby>みを<ruby>我慢<rp>(</rp><rt>がまん</rt><rp>)</rp></ruby>しました。', en: 'I endured the pain.' },
      { ja: '大会で優勝しました。', jaHtml: '<ruby>大会<rp>(</rp><rt>たいかい</rt><rp>)</rp></ruby>で<ruby>優勝<rp>(</rp><rt>ゆうしょう</rt><rp>)</rp></ruby>しました。', en: 'I won the championship.' },
      { ja: '毎日運動させられています。', jaHtml: '<ruby>毎日<rp>(</rp><rt>まいにち</rt><rp>)</rp></ruby><ruby>運動<rp>(</rp><rt>うんどう</rt><rp>)</rp></ruby>させられています。', en: 'I am being made to exercise every day.' },
      { ja: '弟に宿題を手伝わせられました。', jaHtml: '<ruby>弟<rp>(</rp><rt>おとうと</rt><rp>)</rp></ruby>に<ruby>宿題<rp>(</rp><rt>しゅくだい</rt><rp>)</rp></ruby>を<ruby>手伝<rp>(</rp><rt>てつだ</rt><rp>)</rp></ruby>わせられました。', en: 'I was made to help my younger brother with homework.' },
      { ja: '部屋を掃除させられました。', jaHtml: '<ruby>部屋<rp>(</rp><rt>へや</rt><rp>)</rp></ruby>を<ruby>掃除<rp>(</rp><rt>そうじ</rt><rp>)</rp></ruby>させられました。', en: 'I was made to clean the room.' },
    ],
  };
})(window);
