#!/usr/bin/env python3
"""Build kanji-quiz-data.js from the per-level kanji lists.

Reuses kanji-sheets/data/n{level}.json (see generate_kanji_data.py) so the
web quiz's kanji set, meanings, and order always match the printable
sheets — one source of truth. Written as a plain script assigning to
`window`, matching kana.js's own style (no fetch/build step needed to run
the site), rather than JSON fetched at runtime.

Usage:
    python3 scripts/generate_kanji_quiz_data.py
"""
import json
from pathlib import Path

REPO_ROOT = Path(__file__).resolve().parent.parent
DATA_DIR = REPO_ROOT / "kanji-sheets" / "data"
OUT_PATH = REPO_ROOT / "kanji-quiz-data.js"
LEVELS = [5, 4, 3, 2, 1]

HEADER = """(function (global) {
  'use strict';

  // Generated by scripts/generate_kanji_quiz_data.py from
  // kanji-sheets/data/n{level}.json — do not hand-edit.
  global.KANJI_QUIZ_DATA = {
"""

FOOTER = """  };
})(window);
"""


def js_string(s):
    return json.dumps(s, ensure_ascii=False)


def main():
    lines = [HEADER]
    for level in LEVELS:
        items = json.loads((DATA_DIR / f"n{level}.json").read_text())
        entries = ", ".join(
            f'{{ kanji: {js_string(it["kanji"])}, meaning: {js_string(it["meaning"])} }}'
            for it in items
        )
        lines.append(f"    n{level}: [{entries}],\n")
        print(f"N{level}: {len(items)} entries")
    lines.append(FOOTER)

    OUT_PATH.write_text("".join(lines))
    print(f"-> {OUT_PATH.relative_to(REPO_ROOT)}")


if __name__ == "__main__":
    main()
