#!/usr/bin/env python3
"""Build confusable-kanji-data.js from kanji-sheets/data/confusable_kanji_groups.json.

The groups file holds clusters of visually similar kanji (found via
pixel-overlap similarity on rendered glyphs, plus a small manually verified
supplement — see the "Confusing Kanji" feature notes) that share the same
JLPT-order meaning/level fields as the rest of the site's kanji data. This
script just reshapes that JSON into the `window.CONFUSABLE_KANJI_GROUPS`
global the site's plain-script pages expect, matching the convention used
by scripts/generate_kanji_quiz_data.py.

Usage:
    python3 scripts/generate_confusable_kanji_data.py
"""
import json
from pathlib import Path

REPO_ROOT = Path(__file__).resolve().parent.parent
DATA_PATH = REPO_ROOT / "kanji-sheets" / "data" / "confusable_kanji_groups.json"
OUT_PATH = REPO_ROOT / "confusable-kanji-data.js"

HEADER = """(function (global) {
  'use strict';

  // Generated by scripts/generate_confusable_kanji_data.py from
  // kanji-sheets/data/confusable_kanji_groups.json — do not hand-edit.
  global.CONFUSABLE_KANJI_GROUPS = """

FOOTER = """;
})(window);
"""


def main():
    groups = json.loads(DATA_PATH.read_text())
    body = json.dumps(groups, ensure_ascii=False, indent=2)
    OUT_PATH.write_text(HEADER + body + FOOTER)
    total_kanji = sum(len(g["kanji"]) for g in groups)
    print(f"{len(groups)} groups, {total_kanji} kanji")
    print(f"-> {OUT_PATH.relative_to(REPO_ROOT)}")


if __name__ == "__main__":
    main()
